from typing import Any, TypeVar, Generic

T = TypeVar("T")

class Cache(Generic[T]):
    def __init__(self, maxsize: int = 0) -> None: ...
    def get(self, key: Any) -> T | None: ...
    def __setitem__(self, key: Any, value: T) -> None: ...
    def clear(self) -> None: ...
    def memoize(self) -> Any: ...
